language: python
python:
  - "2.6"
  - "2.7"


install: "pip install mock==2.0.0 requests==2.11.1 codecov"

script: python setup.py install && python tests/tests.py

after_success:
  - codecov

branches:
    - travis_stable
